/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import InternalLogic.GameControl;
import InternalLogic.GameControl;
import java.awt.BorderLayout;
import java.awt.Button;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Panel;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import javax.imageio.ImageIO;
import javax.swing.AbstractButton;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JToggleButton;
import javax.swing.SwingUtilities;

/**
 *
 *  Joseph Zhong
 *  Minesweeper - Java (v2.85)
 *  This program is the GUI Object for my overall Minesweeper Project
 *  Minesweeper - GUI Object
 *  1 April 2014
 *
 */


public class MinesweeperGUI extends javax.swing.JFrame
{
    // visual stuff
    private static final int EASY_X = 500;
    private static final int EASY_Y = 500;

    private static final int MEDIUM_X = 700;
    private static final int MEDIUM_Y = 700;

    private static final int HARD_X = 1024;
    private static final int HARD_Y = 640;

    private static Dimension FrameSize;
    private static Dimension PanelSize;

    private static GameControl MainManager;
    private static MinesweeperButton[][] ButtonGrid;

    private static boolean isGridConstructed;

    /**
     * Creates new form MinesweeperGUI
     */
    public MinesweeperGUI()
    {
        isGridConstructed = false;
        initComponents();
        this.setTitle("Minesweeper v1");
        JTextArea test = new JTextArea(instructions(), 5, 35);
        //jPanel1.add(test);

        StringBuilder sb = new StringBuilder(64);
        sb.append("<html>I have something to say, it's beter to burn out then to fade away.").
                        append("  This is a very long String to see if you can wrap with in").
                        append("the available space</html>");

        JLabel label = new JLabel(sb.toString());
        label.setBounds(WIDTH/2, WIDTH/2, WIDTH, WIDTH);
        this.add(label);

        this.setVisible(true);
        this.repaint();
    }

    private String instructions()
    {
        String instructions = "\t\tWelcome to MiArcade (v0.0.2)! "
                + "\nClick on File to get started, or Help for more information."
                + "\n\n\t Keyboard Shortcuts: F2 for New Game";
        return instructions;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        jPopupMenu5 = new javax.swing.JPopupMenu();
        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        javax.swing.JMenu FileMenu = new javax.swing.JMenu();
        NewGameMenu = new javax.swing.JMenu();
        EasyButton = new javax.swing.JMenuItem();
        MediumButton = new javax.swing.JMenuItem();
        HardButton = new javax.swing.JMenuItem();
        QuitButton = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1)
                .addContainerGap(314, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addContainerGap(263, Short.MAX_VALUE))
        );

        FileMenu.setText("File");
        FileMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FileMenuMouseClicked(evt);
            }
        });

        NewGameMenu.setText("New Game");

        EasyButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        EasyButton.setText("Easy");
        EasyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                EasyButtonMouseReleased(evt);
            }
        });
        NewGameMenu.add(EasyButton);

        MediumButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        MediumButton.setText("Medium");
        MediumButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                MediumButtonMouseReleased(evt);
            }
        });
        NewGameMenu.add(MediumButton);

        HardButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        HardButton.setText("Hard");
        HardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                HardButtonMouseReleased(evt);
            }
        });
        HardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HardButtonActionPerformed(evt);
            }
        });
        NewGameMenu.add(HardButton);

        FileMenu.add(NewGameMenu);

        QuitButton.setText("Quit");
        QuitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                QuitButtonMouseReleased(evt);
            }
        });
        FileMenu.add(QuitButton);

        jMenuBar1.add(FileMenu);

        jMenu2.setText("Help");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit method.
     *  Exits the program as does Alt+F4 or Clicking the Red X in the upper right
     *  corner.
     * @param evt User Mouse Click release.
     */
    private void QuitButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuitButtonMouseReleased
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_QuitButtonMouseReleased

    /**
     * Constructor Method.
     * Constructs the easy grid.
     * @param evt
     */

    /*
    private void EasyButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EasyButtonMouseReleased

    }//GEN-LAST:event_EasyButtonMouseReleased
*/
    private void EasyButtonMouseReleased(java.awt.event.MouseEvent evt)
    {
        if(isGridConstructed)
        {
            jPanel1.removeAll();
            constructMinesweeper("easy");
        }
        else
        {
            isGridConstructed = true;
            //jPanel1.removeAll();
            constructMinesweeper("easy");
        }
    }

    private void constructMinesweeper(String difficulty)
    {
        MainManager = new GameControl(difficulty);

        ButtonGrid = new MinesweeperButton[MainManager.getMainGrid().getLength(false)][MainManager.getMainGrid().getLength(true)];
       // produce a GUI grid

        for(int y = 0; y < MainManager.getMainGrid().getLength(false); y++)
        {
            for(int x = 0; x < MainManager.getMainGrid().getLength(true); x++)
            {
                ButtonGrid[y][x] = new MinesweeperButton(" ");
                MouseListener MouseClick;

                MouseClick =  new MouseListener()
                {
                    @Override
                    public void mouseClicked(MouseEvent e)
                    {
//                                throw new UnsupportedOperationException("Not supported yet.");
                        System.out.println("Click Successful");
                    }

                    @Override
                    public void mousePressed(MouseEvent e)
                    {
                        /*
                        AbstractButton abstractButton = (AbstractButton) e.getSource();
                        abstractButton.getModel().setArmed(true);
                        abstractButton.getModel().setPressed(true);
                        * */
                        System.out.println("Press");
                    }

                    @Override
                    public void mouseReleased(MouseEvent e)
                    {
                        AbstractButton abstractButton = (AbstractButton) e.getSource();
                        ArrayList<Object> MouseClickCollection = new ArrayList<>();

                        int y = 0; int x = 0;
                        outerloop:
                        for(y = 0; y < ButtonGrid.length; y++)
                        {
                            for(x = 0; x < ButtonGrid[1].length; x++)
                            {
                                if(abstractButton.equals(ButtonGrid[y][x]))
                                {
                                    break outerloop;
                                    // coordinates saved
                                }
                            }
                        }
                        System.out.println(y + " " + x);

                        // prepare special icons
                        ImageIcon FlagIcon;
                        FlagIcon = new ImageIcon("C://Users/Joseph/Downloads/GitHub/Outside/2013/Minesweeper/src/Images/FlagImage.png");
                        ImageIcon MineIcon;
                        MineIcon = new ImageIcon("C://Users/Joseph/Downloads/GitHub/Outside/2013/Minesweeper/src/Images/MineImage.png");

                        // prepare resize
                        Image MineImage = MineIcon.getImage(); // transform it
                        Image FlagImage = FlagIcon.getImage();

                        int maxSize = Math.max(abstractButton.getHeight(), abstractButton.getWidth()) / 2;

                        Image rescaledImage;
                        ImageIcon imageIcon;



                        MouseClickCollection.add(e.getButton());
                        System.out.println(Arrays.toString(MouseClickCollection.toArray()));

                        int bothMask = MouseEvent.BUTTON1_DOWN_MASK | MouseEvent.BUTTON3_DOWN_MASK;
                        if ((e.getModifiersEx() & bothMask) == bothMask)
                        {
                            System.out.println("Both down");
                        }

                        // right click flag
                        if(SwingUtilities.isRightMouseButton(e)
                                && !SwingUtilities.isLeftMouseButton(e)
                                && !abstractButton.isSelected())
                        {
                            if(!ButtonGrid[y][x].getIsFlagged())
                            {
                                rescaledImage = FlagImage.getScaledInstance(maxSize, maxSize, Image.SCALE_SMOOTH);
                                imageIcon = new ImageIcon(rescaledImage);
                                JLabel iconLabel = new JLabel(imageIcon);
                                abstractButton.add(iconLabel);
                                ButtonGrid[y][x].setIsFlagged(true);
                                MainManager.getMainGrid().flagBox(y, x);
                                resetFont("", y, x);
                            }
                            else
                            {
                                ButtonGrid[y][x].setIsFlagged(false);
                                MainManager.getMainGrid().flagBox(y, x);
                                ButtonGrid[y][x].removeAll();
                                resetFont("", y, x);
                            }
                            /*
                            if(abstractButton.isEnabled())
                            {
                                rescaledImage = FlagImage.getScaledInstance(maxSize, maxSize, Image.SCALE_SMOOTH);
                                imageIcon = new ImageIcon(rescaledImage);
                                JLabel iconLabel = new JLabel(imageIcon);
                                abstractButton.add(iconLabel);

                                abstractButton.setEnabled(false);
                            }
                            else if(!abstractButton.isEnabled())
                            {
                                abstractButton.setEnabled(true);
                                abstractButton.removeAll();
                            }
                            * */

                        }
                        else if(SwingUtilities.isLeftMouseButton(e)
                                && !SwingUtilities.isRightMouseButton(e)
                                && !ButtonGrid[y][x].getIsFlagged())
                        {
                            // leftClick
                            MainManager.getMainGrid().selectBox(y, x);
                            String displayText = MainManager.getMainGrid().getDisplay(y, x);
                            if(displayText.equals("9"))
                            {
                                rescaledImage = MineImage.getScaledInstance(maxSize, maxSize, Image.SCALE_SMOOTH); // scale it the smooth way
                                imageIcon = new ImageIcon(rescaledImage);  // transform it back

                                JLabel test1 = new JLabel(imageIcon);

                                abstractButton.setBackground(Color.red);
                                abstractButton.add(test1);
                            }
                            abstractButton.setText(displayText);

                            resetFont(displayText, y, x);

                                 //break; // apparently that made all the differnece lol

                        }
                        else
                        {
                            abstractButton.setSelected(false);
                        }

                        for(int r = 0; r < ButtonGrid.length; r++)
                        {
                            for(int c = 0; c < ButtonGrid[1].length; c++)
                            {
                                // check for zeros
                                String displayText = MainManager.getMainGrid().getDisplay(r, c);
                                if(!(displayText.equals("_"))
                                        && !displayText.equals("!"))
                                {
                                    ButtonGrid[r][c].setSelected(true);
                                    ButtonGrid[r][c].setText(displayText);

                                    resetFont(displayText, r, c);
                                }
                            }
                        }
                    }

                    @Override
                    public void mouseEntered(MouseEvent e)
                    {
                        //throw new UnsupportedOperationException("Not supported yet.");
                        AbstractButton abstractButton = (AbstractButton) e.getSource();
                        abstractButton.getModel().setArmed(true);
                    }

                    @Override
                    public void mouseExited(MouseEvent e)
                    {
                        //throw new UnsupportedOperationException("Not supported yet.");
                        AbstractButton abstractButton = (AbstractButton) e.getSource();
                        abstractButton.getModel().setArmed(false);
                    }
                };

                ButtonGrid[y][x].addMouseListener(MouseClick);
                jPanel1.add(ButtonGrid[y][x]);

                System.out.println(y + ", " + x); // debug
            }
        } // end for loop

        // sets panel and frame
        this.setResizable(false); // MUST PUT THIS LINE BEFORE BOUNDS AND SIZES ARE SET

        FrameSize = new Dimension(EASY_X, EASY_Y);
        PanelSize = new Dimension(EASY_X, EASY_Y);

        this.setSize(FrameSize);
        this.setLocation(300, 100);

        jPanel1.setPreferredSize(PanelSize);

        jPanel1.setLayout(new GridLayout(MainManager.getMainGrid().getLength(true), MainManager.getMainGrid().getLength(false)));
        this.setVisible(true);

        this.pack();
    }

    private void leftClick(MouseEvent e)
    {

    }

     private void resetFont(String displayNumber, int _r, int _c)
     {
         int height = ButtonGrid[_r][_c].getHeight() / 2;
         Font numberFont = (new Font("sansserif", Font.BOLD, height));

         ButtonGrid[_r][_c].setFont(numberFont);

         if(displayNumber.equals("9"))
         {
             ButtonGrid[_r][_c].setForeground(new Color(255, 0, 0)); // red
         }
         else
         {
             ButtonGrid[_r][_c].setForeground(new Color(0, 130, 200)); // 0,130,200 is a pretty and solid cyan blue
         }


         ButtonGrid[_r][_c].repaint();
     }

    private void MediumButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MediumButtonMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_MediumButtonMouseReleased

    private void HardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HardButtonActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_HardButtonActionPerformed

    private void HardButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HardButtonMouseReleased
        // TODO add your handling code here:
        MainManager = new GameControl("hard");
    }//GEN-LAST:event_HardButtonMouseReleased

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        //checkF2Key(evt);
        //checkTestCMD(evt);
    }//GEN-LAST:event_formKeyPressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
        for(int r = 0; r < ButtonGrid.length; r++)
        {
            for(int c = 0; c < ButtonGrid[1].length; c++)
            {
                {
                    System.out.println(evt.getX() + " " + evt.getY());
                }
            }
        }


    }//GEN-LAST:event_formMouseReleased

    private void FileMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FileMenuMouseClicked
        // TODO add your handling code here:

        System.out.println("FileMenu Clicked");
    }//GEN-LAST:event_FileMenuMouseClicked

    private void checkF2Key(KeyEvent evt)
    {
        if(evt.getKeyCode() == 113)
        {
            System.out.println(evt.getKeyCode());
            //EasyButtonMouseReleased(null);
            FileMenuMouseClicked(null);
        }
    }

    private void checkTestCMD(KeyEvent evt)
    {
        if(evt.getKeyCode() == 114)
        {
            System.out.println(evt.getKeyCode());
            jPanel1.removeAll();
            constructMinesweeper("test");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MinesweeperGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MinesweeperGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MinesweeperGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MinesweeperGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new MinesweeperGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem EasyButton;
    private javax.swing.JMenuItem HardButton;
    private javax.swing.JMenuItem MediumButton;
    private javax.swing.JMenu NewGameMenu;
    private javax.swing.JMenuItem QuitButton;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    private javax.swing.JPopupMenu jPopupMenu5;
    // End of variables declaration//GEN-END:variables
}
